# Generated by Django 4.1.1 on 2022-09-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_rating_post_post_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="rating",
        ),
        migrations.AddField(
            model_name="rating",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
            ),
        ),
    ]
